### ISSUE TITLE
Handle other Error Status Code

### ISSUE THREAD

**Issue by kishannareshpal** [StelioBraga/weather#1]
https://github.com/StelioBraga/weather/blob/97a2592b41964d760b482922cc2c426f72eeeee9/app/src/main/java/com/mz/weather/MainActivity.java#L58

- [ ] Should handle cases where the searching city was not found or there was an error with the request. Maybe `int statusCode = response.getStatus();` and the use a `switch(statusCode)` (or maybe an IF statement) to check other cases such as `404` or `500` (but 500+ status codes are handled in the `onFailure` block below)

**Comment by StelioBraga** [comment]
fixed on  97a2592
