### ISSUE TITLE
Update `README.md`

### ISSUE THREAD

**Issue by kishannareshpal** [StelioBraga/weather#3]
Android app that aims to show the current weather for some selected cities.

Developed using Android native language (Java) and powered by [OpenWeather's Weather API](https://openweathermap.org/api)

**Comment by StelioBraga** [comment]
renamed on 850a904

**Comment by kishannareshpal** [comment]
Please review my comment at: https://github.com/StelioBraga/weather/commit/850a90439e67cbbfce8ade980a4c8c59912b1d03#r61129449
